### ISSUE TITLE
Is this a Komodo fork?

### ISSUE THREAD

**Issue by jl777** [Fair-Exchange/safecoin#1]
You are listing many komodo features, but dont mention komodo at all.

I dont mind if you fork komodo, but I do mind that you dont give proper attribution. Please correct this

**Comment by Fair-Exchange** [comment]
This is a Komodo fork, yes.   I apologize, the fork is very new, we have made it very clear in our announcement that it is in fact a Komodo fork as well as in the copyright information below.   We are still working on documenting the repo but we have no intent of hiding the fact that this was born out of Komodo, or Zcash for that matter.
