### ISSUE TITLE
fix bug from README.md - Shield to SAFE Discord Server, ID is from Komodo Discord Server

### ISSUE THREAD

**Issue by TKPoseidon** [Fair-Exchange/safecoin#129]
Hello, 
i am from Touriva Dev Team and had seen a bug at the README.md.
The invite shield to the SAFE Discord Server is working, but the Server ID is from Komodo Discord Server, thats why it shows 800 online Community members.
If i create a pull-request, the new shield does't work because you must allow before Server Widgets at SAFE Discord.
**Only these steps needed :**
- allow Widget at SAFE Discord
- change line #3 at README.md to...
`[![discord](https://img.shields.io/discord/398548987218493450.svg?&label=Discord&logo=Discord&color=7289da)](https://discord.gg/rKK7huf)`

[![discord](https://img.shields.io/discord/398548987218493450.svg?&label=Discord&logo=Discord&color=7289da)](https://discord.gg/rKK7huf)

![Discord_server_widget](https://user-images.githubusercontent.com/58012964/94997941-c3a8cc80-05ae-11eb-911c-7323de51f429.png)
![Github_SAFE-discord_wrong_discord_ID](https://user-images.githubusercontent.com/58012964/94997968-e5a24f00-05ae-11eb-98c4-80455b16df76.png)
![Github_shield_SAFE-discord](https://user-images.githubusercontent.com/58012964/94997969-eb983000-05ae-11eb-98a6-fb16516e6c26.png)

**Comment by Fair-Exchange** [comment]
Thank you, we've removed this link for now until we decide if want to enable this.
