### ISSUE TITLE
error: expected primary-expression before ‘<<’ token

### ISSUE THREAD

**Issue by DerAdler** [Fair-Exchange/safecoin#2]
### Describe the issue

Since latest commit da3e4e0 I can not compile any more. Before the latest commit everything worked as expected.

### Actual behaviour + errors

The compiler stops and throws out the following error message:

> In file included from safecoin.h:55:0,
>                  from main.cpp:571:
> safecoin_gateway.h:617:1: error: expected primary-expression before ‘<<’ token
>  <<<< HEAD
>  ^
> safecoin_gateway.h:617:3: error: expected primary-expression before ‘<<’ token
>  <<<< HEAD
>    ^
> safecoin_gateway.h:617:6: error: ‘HEAD’ was not declared in this scope
>  <<<< HEAD
>       ^
> safecoin_gateway.h:618:3: error: expected ‘}’ before string constant
>    "dc8caf80aea016ab0377dffb76e73cfcba02c3ee966e6dcd81acba8138348b25", // Block #60827 Mar 26, 2018 4:22:06 PM
>    ^
> safecoin_gateway.h:618:3: error: expected ‘,’ or ‘;’ before string constant
> safecoin_gateway.h:870:1: error: expected declaration before ‘}’ token
>  };
>  ^
> make[2]: *** [libbitcoin_server_a-main.o] Error 1
>

### Machine specs:
CentOS Linux release 7.4
32 GB
3.10.0-693.21.1.el7.x86_64
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

**Comment by Fair-Exchange** [comment]
Hi there, thanks for the feedback.   This should be fixed now.  If not, please let me know.

Our chain was recently attacked, and we had to go through a fork.  You likely pulled the source at this time.    We are nearly back up and running now, and the source is working.   Thank  you for your feedback and support.

**Comment by DerAdler** [comment]
Hi! Now everything is working again as expected, very good job and thank you.

**Comment by Fair-Exchange** [comment]
Happy to hear it worked :)
