### ISSUE TITLE
No mention of Komodo Platform and you forked the repo.

### ISSUE THREAD

**Issue by ptyx11** [Fair-Exchange/safecoin#3]
This is a supernet/komodo clone. This isn't a fair fork and could possibly be a scam.

**Comment by czefo** [comment]
I can not find the devs for SFE, nor did i create the .or or .io

**Comment by Fair-Exchange** [comment]
Hi there ptyx11, Komodo is actually listed in the copyright information below.   This is absolutely a fork of an open source repo as is every other cryptocurrency other than bitcoin.  Just like Komodo forked zcash.

This is not a clone, as the 50% ICO has been removed and other changes have been made to the emission.   More changes are also coming.   There was no intent to hide the fact that this is a Komodo fork, it was already clear and it will be more clear going forward.   We will also give credit to Zcash, which Komodo forked and then immediately profited off.

In our model, we will not immediately profit off of someone else's work.    There will be a much fairer distribution of the currency.

Thank you.
